global:
  resolve_timeout: 5m

route:
  #group_by: ['prom_alert']
  #group_wait: 10s
  #group_interval: 10s
  #repeat_interval: 1h
  receiver: 'prometheus'
receivers:
- name: 'prometheus'
#  webhook_configs:
#  - url: 'http://192.168.122.130:9090/'
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['prom_alert', 'dev', 'instance']
