global:
    scrape_interval:        15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval:    15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    # scrape_timeout is set to the global default (10s)
    #external_labels:
     #   monitor:            'codelab_monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
       - '192.168.122.100:9093'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "alert.rules"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    - job_name:         'prometheus'
      scrape_interval:  5s
      static_configs:
        - targets:      ['192.168.122.130:9090']

#Node Exporter
    - job_name:         'node_exporter'
      scrape_interval:  5s
      static_configs:
        - targets:      ['192.168.122.110:9100']
        
#Cadvisor
    - job_name:         'cadvisor'
      scrape_interval:  5s
      static_configs:
        - targets:      ['localhost:8080']
