listen:
  port: 4040
  address: "192.168.122.170"

#consul:
#  enable: true
#  address: "localhost:8500"
#  datacenter: dc1
#  scheme: http
#  token: ""
#  service:
#    id: "nginxlog"
#    name: "nginxlog"
#    tags: ["foo", "bar"]

namespaces:
  - name: hls
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
    source:
      files:
        - /var/log/nginx/access.log
    labels:
      app: "hls-server"
      environment: "production"
      foo: "bar"
    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
#    relabel_configs:
#    - target_label: request_uri
#      from: request
#      split: 2
#      matches:
#      - regexp: "^/users/[0-9]+"
#        replacement: "/users/:id"
#    relabel:
#      name: request_uri
#      from: "request"
#      split: 2

    
#  - name: app2
#    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time"
#    source:
#      files:
#        - /var/log/nginx/app2/access.log
