version: '3'

services:
    firefox_1:
        container_name: client_1
        image: jlesage/firefox:latest
        networks:
            transit_ttyd:
                ipv4_address: 172.20.0.10
        ports:
            - "5801:5800"
        volumes:
            - "/dev/shm:/dev/shm"
            #- "/etc/hosts:/etc/hosts"
         #   - "/tmp/firefox1:/config:rw"
        extra_hosts:
            - "video.diverse-team.fr:127.0.0.1"
            - "auth.diverse-team.fr:127.0.0.1"
            - "traefik.diverse-team.fr:127.0.0.1"
            - "db.diverse-team.fr:127.0.0.1"
            - "client1.diverse-team.fr:172.20.0.10"
        labels:
            - "traefik.port=5801"
            - "traefik.frontend.rule=Host:client1.diverse-team.fr"
            - "traefik.protocol=http"
        #command: --shm-size 2g
        
    firefox_2:
        container_name: client_2
        image: jlesage/firefox:latest
        networks:
            transit_ttyd:
                ipv4_address: 172.20.0.20
        ports:
            - "5802:5800"
        volumes:
            - "/dev/shm:/dev/shm"
            #- "/etc/hosts:/etc/hosts"
         #   - "/tmp/firefox2:/config:rw"
        extra_hosts:
            - "video.diverse-team.fr:127.0.0.1"
            - "auth.diverse-team.fr:127.0.0.1"
            - "traefik.diverse-team.fr:127.0.0.1"
            - "db.diverse-team.fr:127.0.0.1"
            - "client2.diverse-team.fr:172.20.0.20"
        labels:
            - "traefik.port=5802"
            - "traefik.frontend.rule=Host:client2.diverse-team.fr"
            - "traefik.protocol=http"
        
    firefox_3:
        container_name: client_3
        image: jlesage/firefox:latest
        networks:
            transit_ttyd:
                ipv4_address: 172.20.0.30
        ports:
            - "5803:5800"
        volumes:
            - "/dev/shm:/dev/shm"
        labels:
            - "traefik.port=5803"
            - "traefik.frontend.rule=Host:client3.diverse-team.fr"
            - "traefik.protocol=http"
        #network_mode: host
        #volumes:
         #   - "/tmp/firefox3:/config:rw"
          #  - "/etc/hosts:/etc/hosts"
            #- "/dev/shm:/dev/shm"
        
    firefox_4:
        container_name: client_4
        image: jlesage/firefox:latest
        networks:
            transit_ttyd:
                ipv4_address: 172.20.0.40
        ports:
            - "5804:5800"
        volumes:
            - "/dev/shm:/dev/shm"
        labels:
            - "traefik.port=5804"
            - "traefik.frontend.rule=Host:client4.diverse-team.fr"
            - "traefik.protocol=http"
        
    #firefox_5:
     #   container_name: client_5
      #  image: jlesage/firefox:latest
       # networks:
        #    transit_ttyd:
         #       ipv4_address: 172.20.0.50
        #ports:
        #- "5805:5800"

networks:
    transit_ttyd:
        external: true
        
        #ipam:
         #   driver: default
          #  config:
           #     - subnet: 172.28.0.0/24
