FROM golang:1.7.3 AS builder

ENV NGINX_HOST "http://192.168.112.5"
ENV METRICS_ENDPOINT "/metrics"
ENV METRICS_ADDR ":9913"
ENV DEFAULT_METRICS_NS "nginx"

USER root

WORKDIR /usr/src

RUN git clone https://github.com/hnlq715/nginx-vts-exporter.git

RUN pwd && ls

WORKDIR /usr/src/nginx-vts-exporter

RUN make && make rpm && make docker

RUN pwd && ls 



FROM picoded/ubuntu-openjdk-8-jdk

WORKDIR /usr/src/nginx-vts-exporter

RUN apt-get update && apt-get install -y --no-install-recommends curl sudo net-tools iputils-ping apt-utils software-properties-common git wget build-essential lsb-release nano make libpcre3 libpcre3-dev zlib1g zlib1g-dev checkinstall

RUN pwd && ls

COPY --from=builder /usr/src/nginx-vts-exporter .

RUN pwd && ls 

RUN cp bin/nginx-vts-exporter /bin/
RUN cp docker-entrypoint.sh /bin/
RUN chmod +x /bin/nginx-vts-exporter

RUN pwd && ls && ls /bin


EXPOSE 9913

#CMD ["/bin/bash"]
#CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
ENTRYPOINT ["docker-entrypoint.sh"]


